language: python
cache:
    - apt
    - pip
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "nightly"
addons:
    apt:
        packages:
            - gfortran
            - libatlas-base-dev
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == nightly ]]; then git clone --depth 50 https://github.com/cython/cython.git && cd cython && python setup.py install; fi
install:
    - pip install -v -r requirements.txt
script:
    - nosetests --with-doctest
